version: "3.6"

services:
  wheesh-db:
    image: postgres:latest
    container_name: wheesh-db
    networks:
      - wheesh-network
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

  wheesh-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wheesh-web
    volumes:
      - .:/wheesh
    networks:
      - wheesh-network
    depends_on:
      - wheesh-db
    links:
      - wheesh-db:wheesh-db
    ports:
      - "8000:8000"
    env_file:
      - .env

networks:
  wheesh-network:
    driver: bridge
    ipam:
      driver: default
