# Generated by Django 4.2.16 on 2024-11-26 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0002_present_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='present',
            options={'verbose_name': 'подарок', 'verbose_name_plural': 'подарки'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'вишлист', 'verbose_name_plural': 'вишлисты'},
        ),
        migrations.AlterField(
            model_name='present',
            name='wishlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presents', to='wishlists.wishlist'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
