# Generated by Django 4.2.16 on 2024-11-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0003_alter_present_options_alter_wishlist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='slug_url',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
