# Generated by Django 4.2.16 on 2025-01-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0004_wishlist_slug_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='present',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
